"""empty message

Revision ID: eee7fed1735d
Revises: 
Create Date: 2022-07-23 10:24:11.881018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee7fed1735d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punch_data',
    sa.Column('punch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('identity', sa.String(length=100), nullable=False),
    sa.Column('day', sa.String(length=100), nullable=False),
    sa.Column('go_time', sa.String(length=100), nullable=True),
    sa.Column('leave_time', sa.String(length=100), nullable=True),
    sa.Column('intervals', sa.String(length=100), nullable=True),
    sa.Column('grp_agree', sa.String(length=100), nullable=True),
    sa.Column('htp_agree', sa.String(length=100), nullable=True),
    sa.Column('is_go_punch', sa.String(length=100), nullable=True),
    sa.Column('is_leave_punch', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('punch_id')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('imageName', sa.LargeBinary(length=65536), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('identity', sa.String(length=100), nullable=False),
    sa.Column('creatime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('imp', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('entrytime', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.String(length=100), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('home', sa.String(length=100), nullable=True),
    sa.Column('marriage', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('creatime', sa.DateTime(), nullable=True),
    sa.Column('imageName', sa.LargeBinary(length=65536), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_data')
    op.drop_table('user_data')
    op.drop_table('punch_data')
    # ### end Alembic commands ###
